name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download clang
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/clang-17.0.6.src.tar.xz
          tar -xf clang-17.0.6.src.tar.xz
          rm clang-17.0.6.src.tar.xz
          mv clang-17.0.6.src clang
      - name: get-cmake
        uses: lukka/get-cmake@v3.29.3
      - name: build
        run: |
          cd clang
          mkdir build
          cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install ..
          cmake --build . && cmake --install .
          ls -r install
      